### ISSUE TITLE
PKCS #11

### ISSUE THREAD

**Issue by jacobalberty** [gozdal/accessl#3]
I'd love to see  this project more lively so I figure I'll open a feature request discussion.

What would the feasibility be to offer a PKCS #11 interface to AcceSSL?
Such an interface would let AcceSSL be used in more software stacks and may even allow depreciation of the OpenSSL engine later if so desired by using engine_pkcs11->AcceSSL_pkcs11 to reduce maintenance burden

**Comment by gozdal** [comment]
Yeah, I pretty much don't have time to take care of it properly.
PKCS#11 seems redundant for my use-case, so I didn't consider that. I'm open though for the code that would implement that

**Comment by jacobalberty** [comment]
I'd be interested in contributing some, at the moment it's redundant for my
use case but the more flexible accessl is the more I can use it for.
