### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by passuf** [gozdal/accessl#4]
I am currently trying to solve a similar problem and I would like to see whether I could use AcceSSL. Do you still maintain the project? When following your build guide, it seems like some dependencies cannot be met on Ubuntu 16.04.

If you do not further maintain the project, could you recommend other libraries following a similar approach? Thanks a lot for your help!

**Comment by gozdal** [comment]
@passuf Unfortunately not really. Haven't tried to build on Ubuntu 16.
